openapi: 3.1.0
info:
  title: Banks API
  description: Bank-tagged endpoints extracted from Bank API specification.
  version: 2.6.6
servers:
  - url: https://sandbox-security-uat.finzly.io/auth/realms/BANKOS.UAT.SANDBOX.CUSTOMER/protocol/openid-connect/token
    description: Authentication
security:
  - oAuth2:
      - roles
tags:
  - name: Bank
    description: To fetch the bank info by routing number.
x-tagGroups:
  - name: Bank APIs
    tags:
      - Bank

paths:
  /v1/banks/{routingNumber}:
    $ref: ./bank-openapi.yaml#/paths/~1v1~1banks~1{routingNumber}
  /v1/banks/search/{routingNumber}:
    $ref: ./bank-openapi.yaml#/paths/~1v1~1banks~1search~1{routingNumber}
  /v1/banks:
    $ref: ./bank-openapi.yaml#/paths/~1v1~1banks

components:
  schemas:
    BankResponse:
      $ref: ./bank-openapi.yaml#/components/schemas/BankResponse
    BankSearchResponse:
      $ref: ./bank-openapi.yaml#/components/schemas/BankSearchResponse
    BankInfoResponse:
      $ref: ./bank-openapi.yaml#/components/schemas/BankInfoResponse
    BadRequestResponse:
      $ref: ./bank-openapi.yaml#/components/schemas/BadRequestResponse
    Error:
      $ref: ./bank-openapi.yaml#/components/schemas/Error
  securitySchemes:
    oAuth2:
      $ref: ./bank-openapi.yaml#/components/securitySchemes/oAuth2
